name: Publish Release
on:
  push:
    tags:
      - v*

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: windows-latest
            args: "--target x86_64-pc-windows-msvc"
            target: "windows"
          - platform: windows-latest
            args: "--target aarch64-pc-windows-msvc"
            target: "windows-aarch64"

    runs-on: ${{ matrix.settings.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Add Rust targets window aarch64
        if: matrix.settings.target == 'windows-aarch64'
        run: rustup target add aarch64-pc-windows-msvc
      
      - name: Cache vcpkg repository
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: vcpkg
          key: vcpkg-repo-${{ hashFiles('vcpkg-configuration.json') }}
          restore-keys: |
            vcpkg-repo-
      
      - name: Set up vcpkg
        if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
      
      - name: Bootstrap vcpkg (if cached)
        if: steps.vcpkg-cache.outputs.cache-hit == 'true'
        run: |
          if (-not (Test-Path ".\vcpkg\vcpkg.exe")) {
            .\vcpkg\bootstrap-vcpkg.bat
          }
        shell: pwsh
      
      - name: Cache vcpkg packages and installed dependencies
        uses: actions/cache@v4
        with:
          path: |
            .\vcpkg\installed
            .\vcpkg\packages
            .\vcpkg\buildtrees
          key: vcpkg-${{ runner.os }}-${{ matrix.settings.target }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.settings.target }}-
            vcpkg-${{ runner.os }}-
      
      - name: Set VCPKG_ROOT environment variable
        run: echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
        
      - name: Validate vcpkg manifest
        run: |
          Write-Host "Validating vcpkg.json syntax..."
          $manifest = Get-Content vcpkg.json | ConvertFrom-Json
          Write-Host "✓ vcpkg.json is valid - Project: $($manifest.name) v$($manifest.version)"
          
          Write-Host "Validating vcpkg-configuration.json syntax..."
          $config = Get-Content vcpkg-configuration.json | ConvertFrom-Json
          Write-Host "✓ vcpkg-configuration.json is valid"
        shell: pwsh
        
      - name: Install ffmpeg static md (x64)
        if: matrix.settings.target == 'windows'
        run: |
          .\vcpkg\vcpkg install --triplet x64-windows-static-md
      
      - name: Install ffmpeg static md (aarch64)
        if: matrix.settings.target == 'windows-aarch64'
        run: |
          .\vcpkg\vcpkg install --triplet aarch64-windows-static-md

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v4
        with:
          script: |
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const notes = latestRelease.data.body || '没有更新信息';
            return notes;

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.15.0
      - name: Install frontend dependencies
        run: pnpm install

      - name: Write Sentry Token
        run: echo "VITE_SENTRY_TOKEN=${{ secrets.SENTRY_TOKEN }}" > ~/.env

      - name: Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          args: ${{ matrix.settings.args }}
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: "${{ steps.get_release.outputs.result }}"
          releaseDraft: true
          prerelease: true