name: Rust Check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: rust-check-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo-check:
    name: cargo check
    runs-on: windows-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: pwsh
        working-directory: src-tauri

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 使用 winget 安装 vcpkg 和 pkg-config
      - name: Install vcpkg and pkg-config
        run: |
          winget install --id=Microsoft.vcpkg -e --accept-package-agreements --accept-source-agreements
          winget install --id=GnuWin32.pkg-config -e --accept-package-agreements --accept-source-agreements

      # 设置 VCPKG_ROOT 环境变量（根据实际路径调整）
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=C:\Program Files\vcpkg" >> $GITHUB_ENV

      # 安装 ffmpeg
      - name: Install ffmpeg with vcpkg
        run: |
          "C:\Program Files\vcpkg\vcpkg.exe" install ffmpeg

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      - name: Cargo check
        run: |
          cargo --version
          cargo check --locked --all-targets
