name: Rust Check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: rust-check-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo-check:
    name: cargo check
    runs-on: windows-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: pwsh
        working-directory: src-tauri

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
      - name: Install ffmpeg
        run: |
          cd vcpkg
          .\vcpkg.exe install ffmpeg
      - name: Add vcpkg to PATH
        run: |
          echo "$env:GITHUB_WORKSPACE\\vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      - name: Cargo check
        run: |
          cargo --version
          cargo check --locked --all-targets
